---
- name: Download
  block:
    - name: Get clickhouse distrib
      ansible.builtin.get_url:
        url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clic>
        dest: "./{{ item }}-{{ clickhouse_version }}.rpm"
        mode: '0644'
      loop: "{{ clickhouse_packages }}"
  rescue:
    - name: Get fallback clickhouse distrib
      ansible.builtin.get_url:
        url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common->
        dest: "./clickhouse-common-static-{{ clickhouse_version }}.rpm"
        mode: '0644'
- name: Install clickhouse packages
  become: false
  ansible.builtin.dnf:
    name:
      - clickhouse-common-static-{{ clickhouse_version }}.rpm
      - clickhouse-client-{{ clickhouse_version }}.rpm
      - clickhouse-server-{{ clickhouse_version }}.rpm
    disable_gpg_check: true
  notify: Start clickhouse process inside container
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
- name: Wait for ClickHouse to be ready on host
  ansible.builtin.wait_for:
    host: 127.0.0.1
    port: 9000
    timeout: 30
- name: Create database logs
  ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
  register: create_db
  failed_when: create_db.rc != 0 and create_db.rc != 82
  changed_when: create_db.rc == 0
